// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ozone.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getLatestOzoneEntry = `-- name: GetLatestOzoneEntry :one
SELECT id, created_at, updated_at, start_time, end_time, running, expected_duration, status_message FROM ozone
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOzoneEntry(ctx context.Context) (Ozone, error) {
	row := q.db.QueryRowContext(ctx, getLatestOzoneEntry)
	var i Ozone
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Running,
		&i.ExpectedDuration,
		&i.StatusMessage,
	)
	return i, err
}

const startOzoneGenerator = `-- name: StartOzoneGenerator :one
INSERT INTO ozone (
    start_time, running, expected_duration
) VALUES ( $1, true, $2)
RETURNING id, created_at, updated_at, start_time, end_time, running, expected_duration, status_message
`

type StartOzoneGeneratorParams struct {
	StartTime        sql.NullTime
	ExpectedDuration int32
}

func (q *Queries) StartOzoneGenerator(ctx context.Context, arg StartOzoneGeneratorParams) (Ozone, error) {
	row := q.db.QueryRowContext(ctx, startOzoneGenerator, arg.StartTime, arg.ExpectedDuration)
	var i Ozone
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Running,
		&i.ExpectedDuration,
		&i.StatusMessage,
	)
	return i, err
}

const stopOzoneGenerator = `-- name: StopOzoneGenerator :one
UPDATE ozone
SET end_time = CURRENT_TIMESTAMP, running = FALSE
WHERE id = $1
RETURNING id, created_at, updated_at, start_time, end_time, running, expected_duration, status_message
`

func (q *Queries) StopOzoneGenerator(ctx context.Context, id uuid.UUID) (Ozone, error) {
	row := q.db.QueryRowContext(ctx, stopOzoneGenerator, id)
	var i Ozone
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Running,
		&i.ExpectedDuration,
		&i.StatusMessage,
	)
	return i, err
}

const updateOzoneEntryStatus = `-- name: UpdateOzoneEntryStatus :one
UPDATE ozone
SET status_message = $1
WHERE id = $2
RETURNING id, created_at, updated_at, start_time, end_time, running, expected_duration, status_message
`

type UpdateOzoneEntryStatusParams struct {
	StatusMessage sql.NullString
	ID            uuid.UUID
}

func (q *Queries) UpdateOzoneEntryStatus(ctx context.Context, arg UpdateOzoneEntryStatusParams) (Ozone, error) {
	row := q.db.QueryRowContext(ctx, updateOzoneEntryStatus, arg.StatusMessage, arg.ID)
	var i Ozone
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Running,
		&i.ExpectedDuration,
		&i.StatusMessage,
	)
	return i, err
}
