name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Test workflow
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: go-test-results
          path: ./test-results

  # Build workflow
  build:
    # self hosted runner to build on a RPI
    runs-on: self-hosted

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # build Docker image for Raspberry Pi
      - name: Build Docker image
        run: |
          docker build \
            --platform linux/arm/v7 \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg PORT=${{ vars.PORT }} \
            -t kylebrandon/plunger-server:latest .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      # Stop and remove the existing container
      - name: Stop and Remove Existing Docker Container
        run: |
          docker stop plunger-server || true
          docker rm plunger-server || true

      # Deploy Docker container
      - name: Run Docker Container
        run: |
          docker run --privileged -d \
            --name plunger-server -it \
            --restart unless-stopped \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e PORT=${{ vars.PORT }} \
            -p ${{ vars.PORT }}:${{ vars.PORT }} \
            -v config-volume:/app/config \
            kylebrandon/plunger-server:latest
